### ISSUE TITLE
No support for higher resolution

### ISSUE THREAD

**Issue by Tais993** [KoukoCocoa/SCPSLSettingChanger#3]
My ultra-wide is very sad.
2560 by 1080 isn't a option.

Would be nice to have the language setting automatically get the Windows language and use that.
And main menu to default automatically instead classic

**Comment by KoukoCocoa** [comment]
When you set 2560x1080, what does SavedResolutionSet show in your computers Registry.txt? I will also add the fix for the default menu not being the default choice (as it’s based on index 0 of the list)

**Comment by KoukoCocoa** [comment]
Fixed in V1.2.2, seen here: https://github.com/KoukoCocoa/SCPSLSettingChanger/releases/tag/V1.2.2
